name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # DEBUG: list dist contents so we can confirm the build output in logs
      - name: Show dist contents (debug)
        run: |
          echo "=== cwd ==="
          pwd
          echo "=== listing repo root ==="
          ls -la
          echo "=== listing dist ==="
          ls -la dist || true
          echo "=== show first 80 lines of dist/index.html ==="
          sed -n '1,80p' dist/index.html || true

      - name: Deploy to GitHub Pages (push to gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
