name: Build and deploy (Vite -> GitHub Pages via gh-pages)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Show dist (debug)
        run: |
          echo "=== dist listing ==="
          ls -la dist || true
          echo "=== head dist/index.html ==="
          if [ -f dist/index.html ]; then sed -n '1,120p' dist/index.html; else echo "dist/index.html missing"; fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
