name: Build Vite + React

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Vite requires Node >= 20.19

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
